### ISSUE TITLE
Unleash created infinite loop when proxy server is down

### ISSUE THREAD

**Issue by yarinsa** [Unleash/proxy-client-react#92]
### Describe the bug

Unleash FlagProvider accepts: startClient, config.

We are passing "startClient={false}" until we have the proxy server setted up. 
The problem is that even when passing "startClient" false Unleash still tries to access the server and infinity (caused infinite loop in our app & to crush)

### Steps to reproduce the bug

Wrap your app with the following:

```
    <FlagProvider
      startClient={false}
      config={{
        url: 'http://localhost:3000',
        clientKey: 'secret-key',
        appName: 'App',
        refreshInterval: 1000 * 60 * 15,
      }}
    >
      <App />
    </FlagProvider>
```

[Reproduction](https://react-d2ls1y.stackblitz.io)

### Expected behavior

Allow passing "maxRetries" in the config. Or at least add in your code "retryInterval" option 

### Screenshots

![Screen Shot 2022-11-16 at 10 04 48](https://user-images.githubusercontent.com/44482362/202122421-03938122-9d47-48a3-a64e-993f30d04203.png)

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

### SDK information (language and version)

(Typescript) "@unleash/proxy-client-react": "^3.4.0", "unleash-proxy-client": "^2.3.0",

**Comment by yarinsa** [comment]
Yes. That's was part of the bug. 
startClient is false. But the provider still wraps the app. 
When user authentication status is changed updateContext is called anyway. 
I would expect updateContext to do nothing if startClient=false.

**Comment by FredrikOseberg** [comment]
> Yes. That's was part of the bug. startClient is false. But the provider still wraps the app. When user authentication status is changed updateContext is called anyway. I would expect updateContext to do nothing if startClient=false.

I think the problem is that the core library is emitting an event when the call fails, and we are listening on that event in this SDK. When we call updateContext that immediately triggers a new fetch, which fails, emits and events and the cycle continues. Let me verify that this is what is happening before I publish a fix.

**Comment by yarinsa** [comment]
I think so. How can I verify this? It looks & sounds like our issue :)

**Comment by FredrikOseberg** [comment]
> I think so. How can I verify this? It looks & sounds like our issue :)

I've merged a fix. Could you try version: `3.4.1-beta.1`

**Comment by yarinsa** [comment]
Sure I will try tomorrow if that's ok

**Comment by FredrikOseberg** [comment]
> Sure I will try tomorrow if that's ok

Of course. Thanks!

**Comment by yarinsa** [comment]
@FredrikOseberg Looks great! Indeed solved the issue. 
One more little question (maybe this is as intended). If I pass enableClient={false} I still see one request going to to our proxy. I am fine with this either way as long as it's happening only once.
I also did the following if startClient=false. I am not sure if it got impact. 

![Screen Shot 2022-11-17 at 10 04 25](https://user-images.githubusercontent.com/44482362/202390441-94f9fd90-974d-4bad-8a96-6abefa782adc.png)
